name: Deploy to XSERVER

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.XSERVER_HOST }}
          username: ${{ secrets.XSERVER_USER }}
          password: ${{ secrets.XSERVER_KEY }}
          local-dir: ./
          server-dir: /xs969605.xsrv.jp/public_html/inhouse/wp-content/plugins/My_Attendance_Tool/
          
