on:
  push:
    branches:
      - 'feature/shiroto*'

jobs:
  deploy-personal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: FTP Deploy to Personal Test
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST_SHIROTO }}
          username: ${{ secrets.FTP_USER_SHIROTO }}
          password: ${{ secrets.FTP_PASS_SHIROTO }}
          server-dir: /labs-ims.com/public_html/shiroto-test/tanpop/wp-content/plugins/My_Attendance_Tool/
          dangerous-clean-slate: false