name: Deploy to XSERVER

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.XSERVER_HOST_s }}
          username: ${{ secrets.XSERVER_USER_s }}
          password: ${{ secrets.XSERVER_KEY_s }}
          local-dir: ./
          server-dir: /labs-ims.com/public_html/tanpoposub-test.labs-ims.com/wp-content/plugins/My_Attendance_Tool/
          
